# Generated by Django 4.0 on 2023-03-16 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pension',
        ),
    ]
